### ISSUE TITLE
West and East in the wrong direction

### ISSUE THREAD

**Issue by TabeaW** [JuliaPlots/GeoMakie.jl#113]
Thanks for the great GeoAxis! Only problem at the moment, west and east for the ticks is the wrong way around. East should be positive and west negative. (Sorry, I'm currently not able to create a pull request...)

**Comment by asinghvi17** [comment]
Thanks for reporting, I did mix those up.  I patched it on my PR branch but don't have the bandwidth to fix master right now.  You can monkeypatch it for now with:
```julia
function GeoMakie.longitude_format(nums)
    labels = fill("", length(nums))
    for i in 1:length(nums)
        east_or_west = if nums[i] < 0
            'W'
        elseif nums[i] > 0
            'E'
        else
            ' '
        end
        labels[i] = if round(nums[i]) == nums[i]
            string(Int(abs(nums[i])), "ᵒ $east_or_west")
        else
            string(abs(nums[i]), "ᵒ $east_or_west")
        end
    end
    return labels
end
```


My hope is that I can do some work on #109 this week and get it moving.  The progress there is pretty good, but there are some weird bugs I'm still not understanding so will need some time and help to figure out what's going on.
