### ISSUE TITLE
Please, stop breaking this package on the main outlets.

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GeoMakie.jl#29]
Hi @asinghvi17 , please stop pushing directly to the master branch and instead use pull requests that are merged only once it is ensured that the package is _at least possible to be `using`_.

Every time I try to load `GeoMakie` with a distance of more than a week, it is almost guaranteed that the package won't even load. This is an extremely unpleasant experience, and I'd appreciate it so much if it stopped happening.

So, please, please, as far as the `master` branch and the stable releases go, only push things there if they pass some elementary tests, e.g. that the package can load. It shouldn't be hard to not push PRs that don't even allow `using` the package.

---

If the experience of just using this is so frustrating from the very first command (`using GeoMakie`), it is difficult for users to give feedback and help improve this. You may know the source of this package inside out, but trust me, even something trivial as `Top not defined` is impossible to fix for someone that has no experience with the source.

**Comment by visr** [comment]
To be fair, the README clearly states

> This package is **in development** and will **break often**.

That said, I'd be nice to at least verify releases work and pass tests.

**Comment by Datseris** [comment]
I have seen that note. One can safely assume that anything in a PR is in development and potentially breaking for any package not yet in 1.0. GeoMakie.jl is not special in this respect, I think that is a valid assumption for most packages.

However, the question is: is there any gain on doing all of this breaking changes on `master` branch and release tags? I don't think so, simply because I can't find any "cost" associated with using a different branch and doing pull requests.

In fact, I can only find benefits, since in the Pull Requests travis will find your bugs for you.

**Comment by asinghvi17** [comment]
Yeah, I've been pretty lackadaisical about this so far, I'll separate the master and development branches going forward.

**Comment by asinghvi17** [comment]
I could actually test this on Gitlab, now that you mention it.  Worth a shot for sure.

**Comment by Datseris** [comment]
Thanks a lot of understanding. I sincerely want to help this package move forward, and report bugs and pull requests. Resolving what I report here will only make things smoother and allow me to help more.

**Comment by gaelforget** [comment]
I had imagined advertising `geomakie` at [this ocean sciences 2020 workshop on Tuesday](https://agu.confex.com/agu/osm20/meetingapp.cgi/Session/92105) but I now realize that this would be premature. Will keep an eye out for the next passing release and try `geomakie` again at that point.

Thanks for developing this!

**Comment by asinghvi17** [comment]
Tests pass so far, but the documentation isn't deploying because I forgot how to use Documenter :D

**Comment by asinghvi17** [comment]
P.S. It would be great if you could give a little mention of this to see what people would want out of such a package, since I doubt that I'll get too close to the user-friendliness of cartopy (on the other hand, this is really fast)

**Comment by niclasmattsson** [comment]
This package is filling a void in the Julia ecosystem and is already extremely useful even though it's still under heavy development and undergoing API changes.  So @asinghvi17, could you consider tagging a pre-alpha release ASAP that we can add in our downstream packages? Just a version with minimal changes to the existing code so GeoMakie compiles without errors or warnings. Then we can use the current functionality as is.

For example, there are still nasty warnings during precompilation:

```
WARNING: method deletion during Module precompile may lead to undefined behavior
  ** incremental compilation may be fatally broken for this module **

WARNING: method deletion during Module precompile may lead to undefined behavior
  ** incremental compilation may be fatally broken for this module **
```

This is related to #25 but the warnings are different. As a quick fix, maybe just rename your functions instead of removing methods from Base?

**Comment by asinghvi17** [comment]
That's actually a hack around an AbstractPlotting issue, which I can't remove without breaking some recipes.  I can remove the deletion warnings, but not most of the method definition warnings...FWIW, they don't actually do anything.

**Comment by niclasmattsson** [comment]
Thanks. I brought it up because I hesitate to add GeoMakie to my package because of the scary warnings (I'm fine with your explanation but users of my package won't know this). If you can figure out a simple way to get rid of them then please do - and tag a release which was my main point. :)

(BTW: Is that the "0-argument recipes" issue you mentioned in the other thread? Is that issue in AbstractPlotting's repo? I searched but couldn't find it.)

**Comment by asinghvi17** [comment]
I haven't filed an issue because it's on my radar, but yeah.  I can work around it, though - it'll be a little unclean, but that's fine, because we're overhauling AbstractPlotting's recipes anyway.

**Comment by asinghvi17** [comment]
@niclasmattsson I think I've fixed most of the warnings, and I just tagged a release.  Let me know if you see any, and I can try to fix and tag another one.

**Comment by niclasmattsson** [comment]
Yes, it seems to be working now without warnings. Thank you very much!

**Comment by Datseris** [comment]
@asinghvi17 can you please tag the current masters, since they are working, so that we can free and pin all these packages and continue using GeoMakie in a more safe environment? This way, we also have the safety of trying out new things in a different project/branch without worrying breaking the things we use in "work environment".

**Comment by asinghvi17** [comment]
@Datseris there should be a release from last night, and all relevant masters have been recently (within 1 day) tagged.

**Comment by Datseris** [comment]
Alright, I am freeing:

- GeoMakie
- AbstractPlotting
- MakieLayout

I've noticed that `[b38be410] ↓ FreeType v3.0.0 ⇒ v2.1.1` happened while freeing AbstractPlotting.

Then, after precompiling I got:
```
WARNING: Method definition coastlines() in module GeoMakie at C:\Users\m300808\.julia\packages\AbstractPlotting\3uXXp\src\recipes.jl:152 overwritten at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:21.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition coastlines!() in module GeoMakie at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:22 overwritten at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #coastlines!(Any, typeof(GeoMakie.coastlines!)) in module GeoMakie overwritten.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition earth() in module GeoMakie at C:\Users\m300808\.julia\packages\AbstractPlotting\3uXXp\src\recipes.jl:152 overwritten at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:62.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition earth!() in module GeoMakie at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:63 overwritten
at C:\Users\m300808\.julia\packages\GeoMakie\sgu5N\src\recipes\stock.jl:64.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #earth!(Any, typeof(GeoMakie.earth!)) in module GeoMakie overwritten.
  ** incremental compilation may be fatally broken for this module **

julia> 
```

**Unfortunately**, freeing the packages broke everything. Using the same identical code I've been using so far produces this:

![image](https://user-images.githubusercontent.com/19669089/74749275-335d8780-526a-11ea-991f-df14ec070109.png)

while before freeing it would produce something like this:

![cldarea_total_daynight_mon_avg](https://user-images.githubusercontent.com/19669089/74749327-453f2a80-526a-11ea-8d11-0240b6a04e79.png)

Was it a huge mistake to free everything?

**Comment by Datseris** [comment]
Here is my full status:
```
Project AlbedoProperties v0.0.0
    Status `C:\Users\m300808\ownCloud\Projects\AlbedoProperties\Project.toml`
  [537997a7] AbstractPlotting v0.9.17
  [fbb218c0] BSON v0.2.5
  [8f4d0f93] Conda v1.4.1
  [0703355e] DimensionalData v0.7.1 [`C:\Users\m300808\.julia\dev\DimensionalData`]
  [634d3b9d] DrWatson v1.9.0
  [db073c08] GeoMakie v0.1.1
  [5ab0869b] KernelDensity v0.5.1
  [2fda8390] LsqFit v0.10.0
  [ee78f7c6] Makie v0.9.5
  [5a521ce4] MakieLayout v0.2.15
  [85f8d34a] NCDatasets v0.9.6 #master (https://github.com/Alexander-Barth/NCDatasets.jl.git)
  [9a7e659c] Proj4 v0.6.0
  [438e738f] PyCall v1.91.3
  [d330b81b] PyPlot v2.8.2
  [189a3867] Reexport v0.2.0
  [ade2ca70] Dates
  [10745b16] Statistics
```

**Comment by asinghvi17** [comment]
You're on GeoMakie 0.1.1, the latest tagged version is 0.1.3.

**Comment by Datseris** [comment]
You are correct, I was not in latest releases. I've updated but there are errors:
```
ERROR: LoadError: MethodError: no method matching coastlines!(::Scene,
::Int64; crs=(src = Projection("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"), dest = Projection("+proj=wintri +lon_0=0 +lat_1=0 +x_0=0 +y_0=0 +units=m +ellps=GRS80")))
Closest candidates are:
  coastlines!(::Union{AbstractScene, AbstractPlotting.ScenePlot}; attributes...) at C:\Users\m300808\.julia\packages\GeoMakie\4QOPe\src\recipes\stock.jl:34
  coastlines!(::Attributes, ::Any...; kw_attributes...) at C:\Users\m300808\.julia\packages\GeoMakie\4QOPe\src\recipes\stock.jl:48
  coastlines!(::Union{AbstractScene, AbstractPlotting.ScenePlot}, ::Attributes, ::Any...; kw_attributes...) at C:\Users\m300808\.julia\packages\GeoMakie\4QOPe\src\recipes\stock.jl:53
Stacktrace:
 [1] top-level scope at C:\Users\m300808\Desktop\test.jl:18
in expression starting at C:\Users\m300808\Desktop\test.jl:18
```

I am running the first example of the readme:
```
using Makie, GeoMakie, Proj4, MakieLayout

lons = LinRange(-179.5, 179.5, 360)
lats = LinRange(-89.5, 89.5, 180)

field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

source = LonLat()
dest = WinkelTripel()

xs, ys = xygrid(lons, lats)
Proj4.transform!(source, dest, vec(xs), vec(ys))

scene = surface(xs, ys; color = field, shading = false, show_axis = false, scale_plot = false)

geoaxis!(scene, -180, 180, -90, 90; crs = (src = source, dest = dest,))

coastlines!(scene, 1; crs = (src = source, dest = dest,))
```

**Comment by Datseris** [comment]
I think you've mentioned a change in how `coastlines!` uses the projections, but I didn't write it down... could you please update the readme? 

Ps.: This is a good point to realize that the readme should be updated with every breaking change in order to be runnable.

**Comment by asinghvi17** [comment]
You have to remove the 1 in coastlines, will do that now.

**Comment by Datseris** [comment]
Yes, that worked. Does `geoaxis!` or `coastlines!` now automnatically enforce equal aspect ratio? I've changed the window size a bit but the aspect ratio automatically remained equal (this is a good feature if true).

**Comment by asinghvi17** [comment]
No, that's from the `scale_plot = false` :)

**Comment by Datseris** [comment]
For anyone seeing this, the following versions work for me. I'll keep them pinned for my work project and keep following the dev branches on my home pc:

```
  [537997a7] AbstractPlotting v0.9.20
  [db073c08] GeoMakie v0.1.3
  [ee78f7c6] Makie v0.9.5
  [5a521ce4] MakieLayout v0.2.16
  [9a7e659c] Proj4 v0.6.0
```
