### ISSUE TITLE
Example of how to configure attributes, e.g. color of lat/lon grid in geoaxis!()

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaPlots/GeoMakie.jl#32]
I'd like to reduce the opacity of the latitude and longitude grid lines that get rendered by geoaxis!(). Is this currently possible? If so, could you show how to modify the code of the README example to do this? If not, consider this a feature request (to be able to modify figure properties in general).

**Comment by asinghvi17** [comment]
You can do that pretty easily - just set `color` to, e.g., `RGBA(colorant"gray", 0.2)`.  You might have to `using Colors` or `using GeoMakie.Colors` as well.

**Comment by asinghvi17** [comment]
Ahh, no, I'm wrong here - I forgot that I nested `geoaxis` attributes a while ago.  You should be able to change the color by providing `x = (tick = (color = RGBA(colorant"gray", 0.2),),)` and `x = (tick = (color = RGBA(colorant"gray", 0.2),),)` as keyword arguments.  You can also set them after the fact, for example:
```julia
ga = geoaxis!(scene, -180, 180, -90, 90)[end] # or whatever limits you need
ga.x.tick.color = RGBA(colorant"gray", 0.2)
ga.y.tick.color = RGBA(colorant"gray", 0.2)
```

**Comment by niclasmattsson** [comment]
Perfect, thanks!
