### ISSUE TITLE
Mention GeoMakie.jl in Awesome-Geospatial

### ISSUE THREAD

**Issue by scls19fr** [JuliaPlots/GeoMakie.jl#36]
Hello,

Maybe GeoMakie should be mentioned in 
https://github.com/sacridini/Awesome-Geospatial#julia

Kind regards

**Comment by visr** [comment]
Would be good, yes. Feel free to make a PR there. I see most of the list is from 3 years ago, could use an update. Some should be removed and some added.

**Comment by scls19fr** [comment]
https://github.com/sacridini/Awesome-Geospatial/pull/41 merged
