### ISSUE TITLE
Plotting Coastlines with ortographic projection

### ISSUE THREAD

**Issue by disberd** [JuliaPlots/GeoMakie.jl#47]
Hello, 

I was trying out this nice package and found an issue when trying to run the example on the repository landing page using a destination projection that does not represent the full earth (like the ortographic one for example).

Here is the code I used to run the example

```julia
using GeoMakie, Makie

lons = LinRange(-89.5, 89.5, 180)
lats = LinRange(-89.5, 89.5, 180)

field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

source = GeoMakie.LonLat()
# dest = GeoMakie.Proj4()
dest = GeoMakie.Projection("+proj=ortho")

xs, ys = GeoMakie.xygrid(lons, lats)
GeoMakie.Proj4.transform!(source, dest, vec(xs), vec(ys))

scene = Makie.surface(xs, ys; color = field, shading = false, show_axis = false, scale_plot = false)

GeoMakie.geoaxis!(scene, extrema(lons), extrema(lats); crs = (src = source, dest = dest,))

GeoMakie.coastlines!(scene; crs = (src = source, dest = dest,))
```
which throws an error `transform error: tolerance condition error` at the last line coming from the Proj4 dependency.

The problem is that the `transform` function from the `proj` library return an err code when a single point is provided to the function and this lies outside of the visible earth in the projection.
When multiple points are provided to the `transform` function instead, points that lie outside of the visible earth are simply transformed to `Inf` without throwing an error.
This error could then be solved either by changing the behavior of Proj4 (maybe with a flag or something to disregard error code -20 related to this transformation problem), or by passing the vector of coastlines point to the plot function as a full vector instead of doing it point-by-point.

I decided to open an Issue here because I thought the latter would be preferable if possible but being quite new to Julia and especially Makie I am not sure how much problematic following this approach could be.

**Comment by asinghvi17** [comment]
This is something I figured would happen eventually :) - the solution on GeoMakie's end is to check the limits of the projection and filter the lines appropriately, but I am not sure exactly how that might be done.

**Comment by disberd** [comment]
So Makie always inherently plot vectors in a _broadcast_ way?

I did try a simple workaround without really knowing anything about how Makie works and I can reliably generate the coastlines in the ortographic projection by calling `lines` with the pre-computed vector instead of coastlines.

```julia
import GeoMakie, Makie

lons = LinRange(-89.5, 89.5, 180)
lats = LinRange(-89.5, 89.5, 180)

field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

source = GeoMakie.LonLat()
dest = GeoMakie.Projection("+proj=ortho")

xs, ys = GeoMakie.xygrid(lons, lats)
GeoMakie.Proj4.transform!(source, dest, vec(xs), vec(ys))

scene = Makie.surface(xs, ys; color = field, shading = false, show_axis = false, scale_plot = false)

GeoMakie.geoaxis!(scene, extrema(lons), extrema(lats); crs = (src = source, dest = dest,))

proj_lines = GeoMakie.Proj4.transform(source,dest,hcat(first.(GeoMakie.COASTLINES_LINEVEC),last.(GeoMakie.COASTLINES_LINEVEC)))
xl,yl = proj_lines[:,1],proj_lines[:,2]

Makie.lines!(scene,xl,yl)
```

Isn't something similar feasible inside GeoMakie? This could be useful also for finding the points outside of the projections, as they would be all the rows equivalent to [Inf Inf]

**Comment by asinghvi17** [comment]
Aha, good point!  The reason I was broadcasting was purely because of my use of Point2f0, which doesn't lend itself to being passed to C functions very well.  I can definitely decompose the vector, transform, and then reconstitute the vector of Point2f0 before plotting.

I can get to this tomorrow, will ping you when I make a PR.

**Comment by disberd** [comment]
Cool!
Thanks a lot

Don't worry if you can't make it tomorrow as Makie is more of a future project as I am trying to learn PlotlyJS decently first.
I stumbled upon this nice repo and noticed this while trying out some things I needed to handle with projections :)

**Comment by visr** [comment]
#84 is still hitting this. Right now the projections are done differently, so this line in the top post is always the case:

> points that lie outside of the visible earth are simply transformed to Inf without throwing an error.

I haven't checked yet if this workaround still works: https://github.com/JuliaPlots/GeoMakie.jl/issues/47#issuecomment-621288976

**Comment by asinghvi17** [comment]
Should be solved now.
