### ISSUE TITLE
Warnings on fresh install

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/GeoMakie.jl#51]
Let me start this issue with a bunch of hearts :heart: :heart: :heart: this package will really help with my current research.

I just want to point out that there are many warnings with the simple example:

```
WARNING: both GeoInterface and GeometryBasics export "LineString"; uses of it in module GeoMakie must be qualified
WARNING: both GeoInterface and GeometryBasics export "Polygon"; uses of it in module GeoMakie must be qualified
WARNING: both AbstractPlotting and GeometryBasics export "Vecf0"; uses of it in module GeoMakie must be qualified
WARNING: both AbstractPlotting and GeometryBasics export "Pointf0"; uses of it in module GeoMakie must be qualified
WARNING: both AbstractPlotting and Base export "Text"; uses of it in module GeoMakie must be qualified
```
Many names from GeoInterface, GeometryBasics, and other packages are conflicting. It would be nice to clean that up and release a new patch. I want to show off the package to my colleagues at work :)

**Comment by asinghvi17** [comment]
Hey!  Unfortunately, all of these are outside of GeoMakie's control.  I've fixed the AbstractPlotting ones, and eventually GeoInterface will be a dependency of GeometryBasics, I think.  As for the last one - that's been a pretty consistent problem.  Not sure what we can do about it, given that Text is a pretty fundamental plot type...

By the way, there are some changes coming to the API as soon as JuliaGeo/Proj4.jl#44 is merged, so be sure to keep an eye out for that.

**Comment by visr** [comment]
> GeoInterface will be a dependency of GeometryBasics

Yeah although that would be the new one at that point: https://github.com/JuliaGeo/GeoInterfaceRFC.jl

But perhaps it would help to not reexport GeoInterface from this package?

@asinghvi17 what do you think about gradually adding support for plotting the GeometryBasics types in this package? Since GeometryBasics is a dependency of Makie, I guess it could also be done in Makie itself. Or we develop it here, and consider moving it to Makie later? For anything that needs PROJ, I think GeoMakie would still be the right place.

**Comment by asinghvi17** [comment]
AFAIK, most GeometryBasics stuff is already plottable as a mesh, GeoMakie just makes it faster by using earcut.  In a couple of weeks, I think the only thing we'll end up needing in GeoMakie are the axis and coastline recipes, and some GeoInterface -> GeometryBasics conversions.

I could definitely not reexport GeoInterface, but switching to use `import` might require a heavier refactor.  I'll see if I can find the time for it this weekend.

**Comment by asinghvi17** [comment]
This particular issue should be fixed now, although if you're on Mac M1 you will have issues.  See #103 for that.
