### ISSUE TITLE
Supporting GeometryBasics geometries

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaPlots/GeoMakie.jl#53]
With GeometryBasics geometries being worked upon in Makie(https://github.com/JuliaPlots/AbstractPlotting.jl/pull/486, https://github.com/JuliaPlots/AbstractPlotting.jl/pull/479), what might be the process to integrate stuff here? Since GeoMakie has Proj4 dependency for map projections, I was wondering if it will inherently work for GeometryBasics geometries or might need some additional work?

**Comment by asinghvi17** [comment]
Any Makie plotting function in 2D should pretty much work (assuming that the data is within bounds of the projection).
