### ISSUE TITLE
Tiny image when plotting a limited lon-lat range in GeoMakie 0.1.14

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaPlots/GeoMakie.jl#56]
Not sure if it's a GeoMakie issue or if the problem is upstream, but just slightly modifying the README example (limiting the lat-lon range and not plotting coastlines) produces weird results in GeoMakie 0.1.14.

```
    lons = LinRange(1, 30, 360)   # lon-lat range for Scandinavia
    lats = LinRange(51, 74, 180)

    field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

    source = LonLat()
    dest = WinkelTripel()

    xs, ys = xygrid(lons, lats)
    Proj4.transform!(source, dest, vec(xs), vec(ys))

    scene = surface(xs, ys; color = field, shading = false, show_axis = false, scale_plot = false)

    geoaxis!(scene, extrema(lons), extrema(lats); crs = (src = source, dest = dest,))
```

GeoMakie 0.1.14 with Makie 0.11.0 (same result with Makie 0.9.5):
<img width="481" alt="makie2" src="https://user-images.githubusercontent.com/33093224/92313304-8c082e00-efca-11ea-9348-6c2db149954a.PNG">

GeoMakie 0.1.10 with Makie 0.9.5:
<img width="481" alt="makie1" src="https://user-images.githubusercontent.com/33093224/92313291-7135b980-efca-11ea-90b8-f1ed8dbcf5d3.PNG">

**Comment by asinghvi17** [comment]
Getting back a bit late, but I was just going through the old issues and noticed this.  This should probably work now with the current master, but with #103 it will definitely work:

```julia
lons = LinRange(1, 30, 360)   # lon-lat range for Scandinavia
lats = LinRange(51, 74, 180)

field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

fig = Figure()
ga = GeoAxis(fig[1, 1]; coastlines = true, title = "Small section of Scandinavia")
surface!(ga, lons, lats, field; shading = false)
fig
```
![iTerm2 T5qX4q](https://user-images.githubusercontent.com/32143268/164993162-874cb4fc-c849-4bd8-9653-58286db05416.png)
Then you can modify the x/y limits as usual!
```julia
xlims!(ga, extrema(lons)); ylims!(ga, extrema(lats))
fig
```
![iTerm2 KBGbhl](https://user-images.githubusercontent.com/32143268/164993199-62941b6f-2b69-4fec-9a79-e6daf5ca49cd.png)

**Comment by visr** [comment]
Glad to see you again @asinghvi17! In your example, wouldn't we want the latter image to be the default? Otherwise people working with non-global data will only see their data very small.

**Comment by asinghvi17** [comment]
That's how it _should_ be done, but likely can't implemented yet :D

Automatic limit finding based on input data runs into the issue that the coastlines and the axis are drawn in the plotting scene, so by default the data extents span the globe.  As of now, there is no way to cause Makie to ignore the coastlines (or the axis, for that matter) when computing data limits.  Unfortunately, I can't quite dedicate enough time to figure this out now, but it should be possible with some fiddling at some point.

Another option is to create a separate Scene to hold the geo-axis, but at that point I would probably have to convert GeoAxis into a layoutable, which would be a decently big project.

**Comment by visr** [comment]
Interesting, thanks!

**Comment by asinghvi17** [comment]
Well, it turned out there was a very easy way to do that!  With #103, now you just need to do:

```julia
lons = LinRange(1, 30, 360)   # lon-lat range for Scandinavia
lats = LinRange(51, 74, 180)

field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

fig = Figure()
ga = GeoAxis(fig[1, 1]; coastlines = true, title = "Small section of Scandinavia")
surface!(ga, lons, lats, field; shading = false)
datalims!(ga)
fig
```
![iTerm2 wnSC0X](https://user-images.githubusercontent.com/32143268/165009108-ff3f43df-27d6-43cb-90e8-30cd203f647f.png)


It turned out that Makie does allow you to get the data limits of a vector of plots, so that's what I used.  It may default to the whole globe if you play around with `ga.scene.plots`, but aside from that it should work.  It will cause issues with a constrained projection like `"+proj=ortho"` or similar if your data extents go beyond the domain of the destination CRS, though.
