### ISSUE TITLE
Something is off at mid longtitude

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GeoMakie.jl#6]
For some reason (which I don't immediatelly see, 

I have:
```
lons = 0.5:1:359.5
lons .- 180 # Proj4 requires this format for longtitude
lats = -89.5:1:89.5

field = rand(length(lons), length(lats), 5)
```
(notice that I've exchange the naming of `lon` and `lat` that you use so that they correspond to [reality](https://en.wikipedia.org/wiki/Geographic_coordinate_system).

and then I do
```
source = WGS84()
dest = Projection("+proj=robin")

points = GeoMakie.transform.(WGS84(), dest, GeoMakie.gridpoints(lons, lats))
faces  = GeoMakie.grid_triangle_faces(lons, lats)

colorfunc(i) = vec(field[:, :, i])
r = 1:size(field)[3]
i = r[1]
scene.plots[1].color = colorfunc(i)
```

which gives me 
![image](https://user-images.githubusercontent.com/19669089/72567052-5dabd600-38b5-11ea-85d5-d8d583404ee2.png)

As you can see, after the mid longitude, the plotting stops weorking properly... :(

**Comment by benelsen** [comment]
I haven't tried to reproduce it, but I noticed the following.
Shouldn't
```julia
lons = 0.5:1:359.5
lons .- 180 # Proj4 requires this format for longtitude
```
be 
```julia
lons = 0.5:1:359.5
lons = lons .- 180
```
or is this just a type from copying it into the issue?

**Comment by Datseris** [comment]
I am beyond retarded. Its really sad living my life. (yes the "fix" was that I had to do `lons .-=` instead)

**Comment by asinghvi17** [comment]
Better fix for this is to add `+lon_0=-180` to the Proj params.
