### ISSUE TITLE
transform_func not working

### ISSUE THREAD

**Issue by visr** [JuliaPlots/GeoMakie.jl#78]
I tried running the example in the readme, and for me it only works if I turn off this line:

https://github.com/JuliaPlots/GeoMakie.jl/blob/a3c333da829ca7446b8d369620454e51ff309f1a/examples/geomakie_new.jl#L16

Otherwise I just get an empty figure.

However then the plot is of course no longer projected and I just get the ugly
![image](https://user-images.githubusercontent.com/4471859/121257051-87500d80-c8ad-11eb-8132-06370f3dee90.png)

I'd like to start trying out https://github.com/JuliaGeo/Proj4.jl/pull/51 as a replacement for https://github.com/JuliaPlots/GeoMakie.jl/blob/master/src/projections.jl. This should be equivalent:
```
ax.scene.transformation.transform_func[] = Makie.PointTrans{2}(Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri +lon_0=0 +lat_1=0 +x_0=0 +y_0=0 +units=m", normalize=true))
```

Which can be verified with
```julia
p = Point2f0(150, -27)

ptrans = GeoMakie.proj(source, dest)
ptrans.f(p)
ptrans.f.([p, p])

ptrans2 = Makie.PointTrans{2}(Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri +lon_0=0 +lat_1=0 +x_0=0 +y_0=0 +units=m", normalize=true))
ptrans2.f(p)
ptrans2.f.([p, p])

ptrans.f(p) == ptrans2.f(p)  # -> true
```

But since neither old nor new projection code produces a plot, with no errors, it's a bit hard to figure out what's wrong.

**Comment by SimonDanisch** [comment]
Oh, I forgot to update the README... This is a working example:
https://github.com/JuliaPlots/GeoMakie.jl/blob/master/test/runtests.jl#L8

**Comment by visr** [comment]
Ah great. Updated them in #79.

And for that example, if I replace the `transform_func` as mentioned, I get the same results, so that is a good sign :)
