### ISSUE TITLE
Where did the docs `index.md` disappear?

### ISSUE THREAD

**Issue by ali-ramadhan** [JuliaPlots/GeoMakie.jl#85]
Noticed that the docs header was mangled (see screenshot below) so I was going to open a PR to fix it but it seems that the `docs/index.md` file is no longer part of the repo?

Or at least the "Edit on GitHub" button links to https://github.com/JuliaPlots/GeoMakie.jl/blob/master/docs/src/index.md which doesn't exist.

![image](https://user-images.githubusercontent.com/20099589/124492983-1e13cb00-dd83-11eb-85e5-b73a7c0dd53e.png)

**Comment by visr** [comment]
The index.md file is not in the repo since it is created as a copy of the readme.md. Header issue is already fixed in #83 :)

**Comment by ali-ramadhan** [comment]
Ah I see that in `make.jl` now. Cool idea!
