### ISSUE TITLE
Large polygons are bad for performance

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/GeoMakie.jl#9]
You can't realistically go above 720x360 in a polygon without running into **serious** performance issues, at least the way I've implemented it currently.  @SimonDanisch is there any way this could be done in the backend, as a nonlinear projection?  It would have to be sort of black-boxed, though.

To give a brief explanation of what's going on now, what I've done is to simply define a mesh based on a regular grid in input space (usually untransformed lat-long), and then transform the points into projected space (whatever target projection is given).  Then, an image is provided as the colour for the mesh.

As I understand it, this is similar to the approach which most people take to deforming images; however, it is much less performant.  Any help optimizing this would be really appreciated.

**Comment by SimonDanisch** [comment]
Is this using poly?

**Comment by asinghvi17** [comment]
Yep

**Comment by SimonDanisch** [comment]
Hm...If you give it a connectivity, that shouldn't be a problem.
Is it the rendering that is slow? a ~259_200 element mesh doesn't sound very big, so I'd be surprised to run into rendering performance problems

**Comment by visr** [comment]
Not sure to which degree the projection part is responsible. But would be good to set that up such that it doesn't allocate a length 2 Vector for each coordinate.

**Comment by asinghvi17** [comment]
I guess it might be?  I get a lot of mouse stutter, and typing speed slows to a crawl.  Replotting something else, like `lines(rand(10))` fixes the issues...

**Comment by asinghvi17** [comment]
> Not sure to which degree the projection part is responsible. But would be good to set that up such that it doesn't allocate a length 2 Vector for each coordinate.

The projection isn't, per se, but we have to deform the image - since projections are a black box, we need to know where the x, y coordinates of the image's grid map to.  Therefore it's unfortunately necessary to allocate that length-2 vector.  On the plus side, though, it only needs to be allocated once, and as long as the data isn't some ridiculously large resolution it should be fine to at least save to png.

**Comment by SimonDanisch** [comment]
Do you have an mwe for pure Makie?

**Comment by asinghvi17** [comment]
So this is really weird:
```julia
using Makie, GeoMakie
lats = LinRange(89.5, -89.5, 1000)
lons = LinRange(-179.5, 179.5, 1000)
points, faces = GeoMakie.triangulated_grid(lons, lats)
cvec = rand(RGBf0, length(points))
``` 
is the setup code.

Now, 
```julia
mesh(points, faces; color = cvec)
```
doesn't cause much of a performance penalty, but the image looks wrong:
![mesh](https://user-images.githubusercontent.com/32143268/73109597-9bba8280-3ed1-11ea-8ff2-69bf59fec6a1.png)
whereas using `poly`, the performance penalty is very bad, but the image looks correct:
```julia
poly(points, faces; color = cvec)
```
![mesh](https://user-images.githubusercontent.com/32143268/73109664-c86e9a00-3ed1-11ea-9c11-245040373c38.png)

**Comment by asinghvi17** [comment]
Nevermind, figured the mesh thing out, forgot to set shading to false.

**Comment by asinghvi17** [comment]
Whoa, this is really fast now...what happened to `poly`, to make it so slow?

**Comment by SimonDanisch** [comment]
btw, surface also works with gridlike but distorted data like this, and has an optimized shader ;)

**Comment by asinghvi17** [comment]
What's the method signature for that?

**Comment by SimonDanisch** [comment]
https://simondanisch.github.io/ReferenceImages/gallery//image_on_surface_sphere/index.html

**Comment by SimonDanisch** [comment]
Yup!

**Comment by asinghvi17** [comment]
Huh, transforming this will be interesting :D - will have to figure some way out of transforming subarrays.  Will be interesting for sure....is there any way to provide a Matrix of Point2f0 or something to the surface instead?

**Comment by asinghvi17** [comment]
Figured it out - just hacked the underlying proj4 implementation :D

**Comment by asinghvi17** [comment]
Again - thanks a lot @simon!  @visr, the situation is a little better now - instead of materializing `ncoords` 2-vectors, I now just create 2 matrices of the same size as the image, which is a bit more space-efficient.  They're created by using a monkeypatch to Proj4 which relies on the old API, but I'd like to upstream it anyway - it's just a relaxation of type constraints in `_transform!`.
