### ISSUE TITLE
v0.3.0 examples somewhat broken

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaPlots/GeoMakie.jl#99]
Glad to see an update with simplified syntax and improved docs! But just FYI in case nobody noticed, there's something wrong with the examples. For instance, this is how the final example in the docs renders:

![download](https://user-images.githubusercontent.com/33093224/149372172-318bf133-e9ed-4df7-a196-729728df36b8.png)

The axis labels are off and the whole map is too zoomed in so it looks rectangular instead of round. Everything renders the same way when I cut & paste the code and try it myself.

**Comment by Datseris** [comment]
@SimonDanisch I don't know what happened. All examples are actually broken: http://juliaplots.org/GeoMakie.jl/dev/#Surface-example  When I originally opened the PR, the examples looked like this:

![image](https://user-images.githubusercontent.com/19669089/149533276-dc8f6d2e-e4c8-40c6-b8bd-90af96f9a07a.png)


for the scatter and surface examples respectively (ignore that surface is dark because of the different shading keyword)

**Comment by lazarusA** [comment]
Same for me. I think is the refactor of autolimits done recently by Simon.  I even tried to manually update the lists afterwards, but is not possible. 

```jl
using GeoMakie, Proj4, GLMakie
trans = Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri",
    always_xy = true)
ptrans = Makie.PointTrans{2}(trans)
# all input data coordinates are projected using this function
lons = -180:180
lats = -90:90
points = [Point2f0(lon, lat) for lon in lons, lat in lats]
rectLimits = FRect2D(Makie.apply_transform(ptrans, points))

fig = Figure(resolution = (1200, 800), fontsize = 22)
ax = GeoAxis(fig[1, 1], source = "+proj=longlat +datum=WGS84", dest = "+proj=wintri",
    title = "Projection: Winkel Tripel", coastlines = true)
limits!(ax, rectLimits) # this line does not work as expected. 
fig
```

**Comment by Datseris** [comment]
Yeah, if you look at the plots the ticks and the actual grid lines on the plot are in complete miss-match

**Comment by SimonDanisch** [comment]
So 0.16 fixes that the projection gets applied incorrectly - which means that now the current limits are getting properly projected by the `PointTrans`, but generate Inf values for the limits:
![image](https://user-images.githubusercontent.com/1010467/149538750-c5eefeb1-2bb2-4c30-9f71-ce3f28ac7f9e.png)

If one uses different limits it works:
```julia
using GeoMakie, Proj4, GLMakie
trans = Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri",
    always_xy = true)
ptrans = Makie.PointTrans{2}(trans)
# all input data coordinates are projected using this function
lons = -170:30:170
lats = -80:30:80
points = [Point2f(lon, lat) for lon in lons, lat in lats]
rectLimits = Rect2f(Makie.apply_transform(ptrans, points))

fig = Figure(resolution = (1200, 800), fontsize = 22)
ax = GeoAxis(fig[1, 1], source = "+proj=longlat +datum=WGS84", dest = "+proj=wintri",
    title = "Projection: Winkel Tripel", coastlines = true, lonticks=lons, latticks=lats)
fig
```
![image](https://user-images.githubusercontent.com/1010467/149538793-8436c081-e8d9-447b-8319-00517975b97e.png)

**Comment by lazarusA** [comment]
Regarding the limits, I did this function, which captures almost all possible output cases. 

```Julia
function setlimits!(ax, ptrans; lonrange = -180:10.0:180, latrange = -90:10.0:90)
    lats = lonrange |> collect
    lons = latrange |> collect
    # avoid PROJ wrapping 180 to -180
    lons[end] = prevfloat(lons[end])
    lats[end] = prevfloat(lats[end])
    points = [Point2f(lon, lat) for lon in lons, lat in lats]
    xytrans = Makie.apply_transform(ptrans, points)
    function checkInfs(xy)
        xy[1] != Inf && xy[2] != Inf && xy[1] != -Inf && xy[2] != -Inf && xy[1] != NaN32 && xy[2] != NaN32
    end
    xytransClean = [1.25xytrans[i] for i in 1:prod(size(xytrans)) if checkInfs(xytrans[i])]
    rectLimits = FRect2D(xytransClean)
    limits!(ax, rectLimits)
end
``

**Comment by Datseris** [comment]
Very nice function, but didn't you say @lazarusA that `limits!` anyways doesn't work with `GeoAxis`?

**Comment by lazarusA** [comment]
Yes, but is as Simon has said above. Is due to the new way the limits are set. Probably we could find the right points in the original Lon-lat system and applied them again. That should work.

**Comment by Datseris** [comment]
> Is due to the new way the limits are set

The best way would be to circumvent this new way and set limits directly from GeoMakie.jl. It is rather straightforward with your function. But I have no clue if this is even possible because I don't know the sequence of the plotting pipeline...

**Comment by Datseris** [comment]
@SimonDanisch , can you please tell us what we can do to progress here and fix this? We cannot use your suggestion for smaller limits, -90 to 90 degrees are mandatory (at least for my applications). We also can't use the code of lazarus here, because it seems that this is a change that needs to happen on the Makie.jl side?

**Comment by visr** [comment]
The projection used in [Simon's example above](https://github.com/JuliaPlots/GeoMakie.jl/issues/99#issuecomment-1013213695) works fine for longitude ±180 and latitude ±90 as well, so there is no need to limit that. The problem with the limits is the bulge on the left and right sides, beyond the corner coordinates. What we see is only the inside of the red rectangle:

![image](https://user-images.githubusercontent.com/4471859/150853908-5459538c-02ce-446e-9088-fb3aa7f11cbf.png)

```julia
julia> using GeoMakie, Proj4
julia> trans = Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri", always_xy = true)
julia> ptrans = Makie.PointTrans{2}(trans)
julia> lons = -180:90:180
julia> lats = -90:90:90
julia> points = [Point2f(lon, lat) for lon in lons, lat in lats]
5×3 Matrix{GeometryBasics.Point{2, Float32}}:
 [-180.0, -90.0]  [-180.0, 0.0]  [-180.0, 90.0]
 [-90.0, -90.0]   [-90.0, 0.0]   [-90.0, 90.0]
 [0.0, -90.0]     [0.0, 0.0]     [0.0, 90.0]
 [90.0, -90.0]    [90.0, 0.0]    [90.0, 90.0]
 [180.0, -90.0]   [180.0, 0.0]   [180.0, 90.0]
julia> points_trans = Makie.apply_transform(ptrans, points)
5×3 Matrix{GeometryBasics.Point{2, Float32}}:
 [-1.00188f7, -1.00188f7]  [-2.00375f7, 0.0]  [-1.00188f7, 1.00188f7]
 [-5.00938f6, -1.00188f7]  [-1.00188f7, 0.0]  [-5.00938f6, 1.00188f7]
 [0.0, -1.00188f7]         [0.0, 0.0]         [0.0, 1.00188f7]
 [5.00938f6, -1.00188f7]   [1.00188f7, 0.0]   [5.00938f6, 1.00188f7]
 [1.00188f7, -1.00188f7]   [2.00375f7, 0.0]   [1.00188f7, 1.00188f7]
```

So the bottom left corner becomes (-1f7, -1f7), the upper left (1f7, 1f7). However note that the left and rightmost points along the equator are outside that box at -2f7 and 2f7 along the x.

I'm not sure how the limits are determined, but the Rect2f function gives the correct limits if you give it all the points both before and after projection:

```julia
julia> latlonlim = Rect2f(points)
GeometryBasics.HyperRectangle{2, Float32}(Float32[-180.0, -90.0], Float32[360.0, 180.0])
julia> trans_lim = Rect2f(points_trans)
GeometryBasics.HyperRectangle{2, Float32}(Float32[-2.0037508f7, -1.0018754f7], Float32[4.0075016f7, 2.0037508f7])
```

**Comment by TabeaW** [comment]
For me it worked to return the change the lines 131 and 132 in axis.jl (Makie). Maybe this breaks something else, but the geoaxis should work fine.

**Comment by Datseris** [comment]
> I'm not sure how the limits are determined, but the Rect2f function gives the correct limits if you give it all the points both before and after projection:

Yes, that's exactly the problem. The current limits that is set automatically from Makie.jl is _not_ using the appraoch you suggested, which is the same as what @lazarusA has suggested. We need to be able to set limits from withing GeoMakie.jl, but that is not possible until we revert the code in Makie.jl, i.e. do the change user @TabeaW has just suggested.

**Comment by Datseris** [comment]
I'd really like to fix this and move my work to GeoMakie. But we also need to update to Makie.jl 0.16. At the moment nothing works:
```julia
fig = GeoMakie.Figure()
ax = GeoMakie.GeoAxis(fig[1,1]; coastlines = true)

ERROR: LoadError: UndefVarError: Transformation not defined
Stacktrace:
 [1] getproperty
   @ .\Base.jl:35 [inlined]
```
It doesn't even tell you where the werror is coming from... @SimonDanisch can you please provide some input of how I'd fix this Transformation error and the limits? I'm happy to put in the work, but I really don't know what to do at the moment.

**Comment by Datseris** [comment]
I've added the limit setting function from @lazarusA to the ongoing PR #100 , but the results are still totally wrong.

**Comment by Datseris** [comment]
Note that the function from lazaro, specifically 
```julia
function geoaxis_setlimits!(ax, ptrans; lonrange = -180:10.0:180, latrange = -90:10.0:90)
    lats = Float32.(lonrange)
    lons = Float32.(latrange)
    # avoid PROJ wrapping 180 to -180
    lons[end] = prevfloat(lons[end])
    lats[end] = prevfloat(lats[end])
    points = [Point2f(lon, lat) for lon in lons, lat in lats]
    xytrans = Makie.apply_transform(ptrans, points)
    check_infs(xy) = !any(x -> isnan(x) || isinf(x), xy)
    xytrans_clean = [1.2xy for xy in xytrans if check_infs(xy)]
    rect_limits = FRect2D(xytrans_clean)
    limits!(ax, rect_limits)
end
```
already does what @visr says, it gives the projected points to Rect2f. Results are still nonsense, though, e.g. running the scatter example from the docs:

![image](https://user-images.githubusercontent.com/19669089/154090700-06b933fb-62e5-469b-a543-ef3e19fa3e61.png)

**Comment by visr** [comment]
It looks like that function does 3 things:

1. Avoid coordinate wrapping with `prevfloat`
2. Filter out coordinates projected to infinity
3. Multiply the bounding box coordinates by 1.2

At least in [this example](https://github.com/JuliaPlots/GeoMakie.jl/issues/99#issuecomment-1020510420) 1 and 2 were not needed. And 3 basically scales the bounding box outside in all directions by 20%, given that the center of the box is 0, 0. So this just scales the red square a bit, but does not solve the problem generally. Also I'd like to avoid the assumtion that 0,0 is in our limits.

**Comment by Datseris** [comment]
Well if 1, 2 are not needed, its not like anything happens wrongly in the code then. I've removed the scaling by 1.2, you are right, it incorrect. The current version
```julia
function geoaxis_setlimits!(ax, ptrans; lonrange = -180:10.0:180, latrange = -90:10.0:90)
    lats = Float32.(lonrange)
    lons = Float32.(latrange)
    # avoid PROJ wrapping 180 to -180
    lons[end] = prevfloat(lons[end])
    lats[end] = prevfloat(lats[end])
    points = [Point2f(lon, lat) for lon in lons, lat in lats]
    xytrans = Makie.apply_transform(ptrans, points)
    check_infs(xy) = any(x -> isnan(x) || isinf(x), xy)
    xytrans_clean = filter(check_infs, xytrans)
    rect_limits = FRect2D(xytrans_clean)
    limits!(ax, rect_limits)
end
```
still doesn't fix the issue:
![image](https://user-images.githubusercontent.com/19669089/154098882-542495c2-7bde-46d0-a8b6-04d601e79873.png)

**Comment by visr** [comment]
> For me it worked to return the change of the lines 131 and 132 in axis.jl (Makie).

I don't fully understand this change, or why it would work @TabeaW, could you elaborate? I did have a look at this place, and indeed I see that this is where the bottom left and top right corners of the limits get projected. These are the red dots here:
<img width="200" alt="150853908-5459538c-02ce-446e-9088-fb3aa7f11cbf" src="https://user-images.githubusercontent.com/4471859/154160052-3b1cb18c-d21a-4490-ac86-51ac3556bb71.png">

In this example it happens to bulge in the middle. So we can instead use the midpoints, the black dots, to project and get better limits, with this hack:

https://github.com/visr/Makie.jl/commit/34400dad10e6bc45f1cbb9913a3cc04eba040f6f
And this code
```julia
using GeoMakie, Proj4, CairoMakie

trans = Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=wintri", always_xy = true)

lons = -180:90:180
lats = -90:90:90

fig = Figure(resolution = (1200, 800), fontsize = 22)
ax = GeoAxis(fig[1, 1], source = "+proj=longlat +datum=WGS84", dest = "+proj=wintri",
    title = "Projection: Winkel Tripel", coastlines = true, lonticks=lons, latticks=lats)
fig
```
To get
![plot_14](https://user-images.githubusercontent.com/4471859/154160580-ac663dd9-2430-42e1-8453-1e78bffb7465.png)

This wouldn't work in general though, say we use a [Vitkovsky I projection](https://proj.org/operations/projections/vitk1.html). For that collecting the projected limits of all the gridlines or datapoints is a better idea, but I'm not sure how to plug that in? Since right now it always transforms on the corner coordinates only.
